### ISSUE TITLE
Weapon

### ISSUE THREAD

**Issue by PandaDasKissen** [Pidroh/HaxeRPGUtilities#18]
I cannot switch weapon.

**Comment by Pidroh** [comment]
What do you mean? Is it an in-game bug?

**Comment by PandaDasKissen** [comment]
It might be a mobile issue, but when I selected a weapon at the beginning of the game, I haven’t been able to change the weapon using the unequip/equip buttons. After refreshing the page it still won’t let me.

This info probably isn’t that useful.

**Comment by Pidroh** [comment]
https://pidroh.github.io/GenericRPGIdle/ this should work but mobile isn't really recommended :(
